version: '3'

services:
  app:
    build: .
    expose:
      - "8008"
    ports:
      - "80:8080"
    volumes:
      - ./build:/app/build
      - ./config:/app/config
      - ./dist:/app/dist:rw
      - ./docs:/app/docs
      - ./src:/app/src
      - ./static:/app/static
      - ./test:/app/test
      - ./package.json:/app/package.json
